### ISSUE TITLE
Can't install the grunt module

### ISSUE THREAD

**Issue by pmd-bgermain** [stpe/grunt-gss-to-json#1]
Hi,

I am trying to install the grunt gss to json for my project and I get a "Failed at the iconv@2.1.7 install script." error that blocks the node module installation.

I looked on internet for iconv error and found that it could be related to python version (I have the v2.7.5).

Any clue on how to fix that ?

**Comment by stpe** [comment]
Try to individually rebuild iconv, like this:
https://github.com/bnoordhuis/node-iconv/issues/37
