### ISSUE TITLE
Dynamic JSON output

### ISSUE THREAD

**Issue by ghost** [stpe/grunt-gss-to-json#2]
Hi there,

This isn't an issue per-say, but rather a question about scope. I wonder if it's possible to read one sheet, and dynamically output JSON if you need multiple files?

Is there scope for reading the Tabs, within a sheet, for example?

**Comment by stpe** [comment]
In the configuration of the task you set which tab (called _worksheet_ in the configuration) to read from. By having multiple targets in the Grunt configuration you can read from different worksheets and apply any special processing/manipulation you want on that data.

However, reading from one sheet and output to multiple files is not possible with the current configuration. Feel free to elaborate on your use case, maybe there is a way.
